version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - run: yarn install
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # run tests!
      - run: yarn test
      - store_artifacts:
          path: test-results.xml

workflows:
  version: 2

  pipeline_dev:
    jobs:
      - build
      - test:
          requires:
            - build
